"""add schedule_exceptions and bookings tables

Revision ID: 2b4bf09a35e7
Revises: 08bdebc379b4
Create Date: 2026-09-19 15:20:51.330070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4bf09a35e7'
down_revision: Union[str, None] = '08bdebc379b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('work_start', sa.String(length=5), nullable=True),
    sa.Column('work_end', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'date', name='uq_post_date_exception')
    )
    op.create_index(op.f('ix_schedule_exceptions_post_id'), 'schedule_exceptions', ['post_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'date', 'start_time', name='uq_post_slot')
    )
    op.create_index(op.f('ix_bookings_date'), 'bookings', ['date'], unique=False)
    op.create_index(op.f('ix_bookings_post_id'), 'bookings', ['post_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_post_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_schedule_exceptions_post_id'), table_name='schedule_exceptions')
    op.drop_table('schedule_exceptions')
    # ### end Alembic commands ###
