"""add schedule_exceptions and bookings tables

Revision ID: ba4f32cb4d62
Revises: 2b4bf09a35e7
Create Date: 2026-09-20 07:52:38.333843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4f32cb4d62'
down_revision: Union[str, None] = '2b4bf09a35e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
