"""add manager_note to users

Revision ID: e2ae3ed48da1
Revises: 78cdc72402de
Create Date: 2026-09-29 19:33:19.863506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ae3ed48da1'
down_revision: Union[str, None] = '78cdc72402de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manager_note', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'manager_note')
    # ### end Alembic commands ###
